### ISSUE TITLE
Wolfgang power, right wolf sinks

### ISSUE THREAD

**Issue by Tswiggs** [Tswiggs/Game-Dev-4358#2]
Wolfgangs right hand wolf sinks if summoned and then the player wiggles wolfgang a bit.  I dont know if this happens when wolfgang is on solid ground and not floating in the air for the initial launch.

**Comment by stu-millner** [comment]
There should be a check in the Wolfgang power update function to ensure
that all three wolves are moving at the same velocity. If a wolf is sinking
and the other two aren't then they aren't moving at the same velocity so
it's probably a good idea to look there first
